# Reference: https://www.digitalocean.com/community/tutorials/how-to-deploy-resilient-go-app-digitalocean-kubernetes
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: stock-quotes-config
data:
  SYMBOL: MSFT
  NDAYS: '7'
  APIKEY: demo   # TODO: replace with a secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-quotes
spec:
  replicas: 1
  selector:
    matchLabels:
      name: stock-quotes
  template:
    metadata:
      labels:
        name: stock-quotes
    spec:
      containers:
      - name: application
        image: ghcr.io/pushittoprod/stock_quotes
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: stock-quotes-config
---
apiVersion: v1
kind: Service
metadata:
  name: stock-quotes
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    name: stock-quotes