# Kubernetes configuration
# Prerequisites: you must configure a secret named stock-quotes-secret with an
# entry named APIKEY containing your Alpha Vantage API key.

# Reference: https://www.digitalocean.com/community/tutorials/how-to-deploy-resilient-go-app-digitalocean-kubernetes
# TODO: put these in a stock-quotes namespace
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: stock-quotes-config
data:
  SYMBOL: MSFT
  NDAYS: '7'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-quotes
spec:
  replicas: 1
  selector:
    matchLabels:
      name: stock-quotes
  template:
    metadata:
      labels:
        name: stock-quotes
    spec:
      containers:
      - name: application
        image: ghcr.io/pushittoprod/stock_quotes
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: stock-quotes-config
        - secretRef:
            name: stock-quotes-secret
---
apiVersion: v1
kind: Service
metadata:
  name: stock-quotes
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    name: stock-quotes
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stock-quotes-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: stock-quotes.get
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: stock-quotes
            port:
              number: 8080