# A quick docker-compose.yml file for testing the Docker build.
version: "3.9"

services:
  quotes:
    build: .
    ports:
    - "8080:8080"
    environment:
      SYMBOL: MSFT
      NDAYS: 7
      APIKEY: demo
